In [1]:
import numpy as np#importing library

mat = np.array([[1, 2,3], [2, 3,4],[5,6,7]]) #create the matrix
print("Printing the Matrix:\n",mat) 

x,y = np.linalg.eig(mat) #to find eigen values and eigen vectors  

print("Eigen values of the matrix:\n",x)# for eigen values  
print("Eigenvectors of the matrix:\n",y)# for eigen vectors

Printing the Matrix:
 [[1 2 3]
 [2 3 4]
 [5 6 7]]
Eigen values of the matrix:
 [ 1.20000000e+01 -1.00000000e+00 -7.75237598e-17]
Eigenvectors of the matrix:
 [[ 0.30996521  0.66666667  0.40824829]
 [ 0.44280744  0.33333333 -0.81649658]
 [ 0.84133414 -0.66666667  0.40824829]]


In [9]:
# Using singular Value Decomposition
import numpy as np

#non-square matrix
A = np.array([[5, 1, 1], [9, 4, 3]])
# Using SVD
U, S, VTrans = np.linalg.svd(A)
# Singular values
singular_values = S
# Left singular vectors : eigen values of A and A transpose
left_singular_vectors = U
# Right singular vectors : eigen values of A transpose and A
right_singular_vectors = VTrans.T

print("Singular Values(lambda):",singular_values)
print("\nLeft Singular Vectors(U):",'\n',left_singular_vectors)
print("\nRight Singular Vectors(VTrans):",'\n',right_singular_vectors)


Singular Values(lambda): [11.48047147  1.09488579]

Left Singular Vectors(U): 
 [[-0.4444721  0.8957927]
 [-0.8957927 -0.4444721]]

Right Singular Vectors(VTrans): 
 [[-0.89582512  0.4372279  -0.07955573]
 [-0.35082556 -0.80565087 -0.47733437]
 [-0.27279805 -0.39969794  0.87511301]]
